### ISSUE TITLE
Add precommit

### ISSUE THREAD

**Issue by agritheory** [agritheory/forecast#20]
@hkuz Are there any special Jupyter notebooks pre-commit hooks that we may want to include as well?

**Comment by HKuz** [comment]
@agritheory - I'll look into if there's a jupyter hook we should use. I do have pre-commit added in both PRs (was in the tox one initially, but sorely needed the formatting hooks in the date binning one too)

**Comment by HKuz** [comment]
Following up from yesterday's call, the only Jupyter hook that seems to be applied by convention is one to remove the cell output before committing. Since our notebook is used for documentation and demonstration purposes, we're opting out of doing that.
